# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: infilos
author: infilos
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.infilos.com
# root: /hexo-theme-doc/

# Writing
relative_link: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ../node_modules/hexo-theme-doc

theme_config:
  favicon: /images/favicon.ico
  google_analytics: UA-123062585-1
  support:
    text: "Didn't find what you are looking for or find some errors? <br /> Try searching again on the left menu or"
    link_text: Raise an Issue on Github.
    link_url: https://github.com/infilos/infilos.github.io/issues/new
    navigation: true
    navigation_label: SUPPORT/FEEDBACK

# turns off breaks on new line in md file. To get a line break add three spaces to the end of the line before the break
marked:
  breaks: false


node_sass:
  includePaths:
   - node_modules

ignore:
  # development only: ignore sub node_modules when `npm link hexo-theme-doc`
  - '**/node_modules/**/*node_modules'

deploy:
  type: git
  repo: git@github.com:infilos/infilos.github.io.git
  branch: gh-pages